# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 943ed92c3236d166becf248c273d50ca8f6564afbdf6b605f104f12b90d89ff448326eedcca6c58980189056210315687f39b26300700a88d55930c32ab92e3c

test:
  secret_key_base: d33ad5e08a6ee0c0290b921ecaca65efff78a6dc3c57d43c4072c27f88159f20cdf42acdf29084a69a6af0c3c1986564953a3c2a47d5267aaace1c326ce22144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
